title: Matt Richardson
description: Matt Richardson's ramblings

url: http://mjrichardson.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Tags
   url: /tags
 - title: Contact
   url: /contact
 - title: About
   url: /about

social:
   github: matt-richardson
   twitter: squire_matt
   facebook: squirematt
   email: matt@redgumtech.com.au

google_analytics: 

exclude : [
	'todo.md', 'README.md', 'LICENSE'
	]
